"""Schema-per-tenant data plane — the mode approved by ADR-003 §2.

Each tenant's analytical data lives in its own PostgreSQL schema. The runtime
role is granted ``USAGE`` on a tenant's schema only when that tenant is
provisioned; it is never blanket-granted, so a compiled query that somehow
named another tenant's schema would be refused by the database itself.

Two safety rules govern every identifier here:

1. **Schema names are derived from the tenant record, never from request
   input** (ADR-003 Risks). ``namespace_for`` takes a ``TenantRef`` whose id
   came from an authenticated membership.
2. **Names are validated and quoted, not interpolated on trust.** PostgreSQL
   has no bind parameters for identifiers, so DDL must interpolate; the
   defence is an allowlist regex plus ``quote_ident`` semantics, applied here
   in one place rather than at each call site.
"""

from __future__ import annotations

import re
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from eip.dataplane.interfaces import (
    DataPlaneHandle,
    DataPlaneHealth,
    DataPlaneInfo,
    DataPlaneStatus,
    TenantRef,
)
from eip.platform.logging import get_logger
from eip.platform.settings import IsolationMode

_log = get_logger("dataplane.schema_per_tenant")

#: PostgreSQL identifiers are limited to 63 bytes.
_MAX_IDENTIFIER_LENGTH: Final = 63
_SAFE_IDENTIFIER: Final = re.compile(r"^[a-z_][a-z0-9_]*$")


class SchemaPerTenantDataPlane:
    """``TenantDataPlane`` over PostgreSQL schemas.

    Uses the ``eip_platform`` engine because provisioning is DDL, which the
    constrained runtime role deliberately cannot perform (guardrail 17: schema
    changes ship as migrations or through the provisioning subsystem, never
    ad hoc from application code).
    """

    def __init__(
        self,
        *,
        platform_engine: AsyncEngine,
        schema_prefix: str,
        runtime_role: str = "eip_app",
    ) -> None:
        self._engine = platform_engine
        self._prefix = schema_prefix
        self._runtime_role = runtime_role
        if not _SAFE_IDENTIFIER.match(runtime_role):
            msg = f"Unsafe runtime role name: {runtime_role!r}"
            raise ValueError(msg)

    @property
    def mode(self) -> IsolationMode:
        return IsolationMode.SCHEMA_PER_TENANT

    # --- naming ----------------------------------------------------------

    def namespace_for(self, tenant: TenantRef) -> str:
        """Derive the tenant's schema name.

        Built from the tenant's UUID rather than its slug: a slug is
        user-supplied and mutable, and a renamed tenant must not orphan its
        data. Hyphens become underscores to satisfy identifier rules.
        """
        suffix = str(tenant.tenant_id).replace("-", "_")
        name = f"{self._prefix}{suffix}"[:_MAX_IDENTIFIER_LENGTH]
        if not _SAFE_IDENTIFIER.match(name):
            msg = f"Derived schema name is not a safe identifier: {name!r}"
            raise ValueError(msg)
        return name

    # --- lifecycle -------------------------------------------------------

    async def provision(self, tenant: TenantRef) -> DataPlaneHandle:
        """Create the tenant's schema and grant the runtime role access.

        Idempotent: re-running is a no-op, so a retried provisioning job is
        safe (ADR-009 idempotency requirement).
        """
        namespace = self.namespace_for(tenant)

        async with self._engine.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{namespace}"'))
            # USAGE only, and only for this tenant's schema. The runtime role
            # never receives CREATE: analytical DDL is generated by this
            # subsystem, not written by application code.
            await conn.execute(text(f'GRANT USAGE ON SCHEMA "{namespace}" TO {self._runtime_role}'))
            await conn.execute(
                text(
                    f'ALTER DEFAULT PRIVILEGES IN SCHEMA "{namespace}" '
                    f"GRANT SELECT ON TABLES TO {self._runtime_role}"
                )
            )

        _log.info("dataplane.provisioned", tenant_id=str(tenant.tenant_id), mode=self.mode.value)
        return DataPlaneHandle(tenant_id=tenant.tenant_id, mode=self.mode, namespace=namespace)

    async def deprovision(self, tenant: TenantRef) -> None:
        """Drop the tenant's schema and everything in it.

        One statement erases a tenant's analytical data completely — the
        offboarding and GDPR-erasure property ADR-003 siloed the data plane to
        obtain.
        """
        namespace = self.namespace_for(tenant)
        async with self._engine.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{namespace}" CASCADE'))
        _log.warning("dataplane.deprovisioned", tenant_id=str(tenant.tenant_id))

    async def handle(self, tenant: TenantRef) -> DataPlaneHandle:
        return DataPlaneHandle(
            tenant_id=tenant.tenant_id,
            mode=self.mode,
            namespace=self.namespace_for(tenant),
        )

    # --- introspection ---------------------------------------------------

    async def describe(self, tenant: TenantRef) -> DataPlaneInfo:
        namespace = self.namespace_for(tenant)
        async with self._engine.connect() as conn:
            exists = (
                await conn.execute(
                    text("SELECT 1 FROM information_schema.schemata WHERE schema_name = :name"),
                    {"name": namespace},
                )
            ).scalar_one_or_none()

        return DataPlaneInfo(
            tenant_id=tenant.tenant_id,
            mode=self.mode,
            namespace=namespace,
            status=DataPlaneStatus.READY if exists else DataPlaneStatus.UNPROVISIONED,
        )

    async def health(self, tenant: TenantRef) -> DataPlaneHealth:
        try:
            info = await self.describe(tenant)
        except Exception as exc:
            return DataPlaneHealth(
                tenant_id=tenant.tenant_id, reachable=False, detail=type(exc).__name__
            )
        return DataPlaneHealth(
            tenant_id=tenant.tenant_id,
            reachable=info.status is DataPlaneStatus.READY,
            detail=info.status.value,
        )
